### ISSUE TITLE
Issues with Event Type Deletion, Metadata, and Endpoint Configuration in Hook0

### ISSUE THREAD

**Issue by ecerroni** [hook0/hook0#16]
First of all kudos for Hook0. Awesome idea with a nice, simple and straightforward UI.

However, after cloning it locally and spinning it up with Docker I found the following issues while playing around

**1. Event Type Deletion**
Once an test event has been used to send a certain event type that same type cannot be deleted anymore, that is when there is one or more event in the event table that have that particular event type,

_Steps to Reproduce:_
Attempt to delete an event type that has been used in the "event" table within the "event" schema.
Notice that the deletion does work.

If you manually delete all events of that type from the table and return to the UI, the deletion works.

_Expected Behavior:_ Event types should be deletable even if they have been used.

**2. Metadata Handling**
As a User I cannot add multiple metadata rows when creating/editing a subscription, and even when setting the only available row, it is not included in the sent object.

_Steps to Reproduce:_
Attempt to add multiple metadata rows while creating/editing a subscription.
Only one row, the first one, is showing and no other can be added by clicking the plus button.
Set the available row, save/update the subscription and send a test event.
No metadata will be included in the sent object.

_Expected Behavior:_ Users should be able to add multiple metadata rows, and all set metadata should be included in the sent object.

**3. Endpoint HTTP Verb and URL Configuration**
Although the HTTP verb and URL are saved correctly, revisiting the edit page defaults the verb to GET.

_Steps to Reproduce:_
Set an HTTP verb, for example POST, and URL for an endpoint.
Save/update the subscription.
Return to the edit page, the verb defaults to GET.
If the user clicks Update without noticing, the verb is incorrectly set to GET.

_Expected Behavior_: The correct HTTP verb should be displayed when revisiting the edit page, preventing accidental changes.

**Comment by FGRibreau** [comment]
Thanks a lot for your report @ecerroni !

I've created the 3 corresponding tickets on our main repository, let's continue the discussion there please :)
- https://gitlab.com/hook0/hook0/-/issues/49
- https://gitlab.com/hook0/hook0/-/issues/50
- https://gitlab.com/hook0/hook0/-/issues/51

We are open-source so we are open for your contribution and help you make into Hook0 next release :)
