### ISSUE TITLE
API Dockerfile: Typo in Rust Base Image Version

### ISSUE THREAD

**Issue by peter-curiousit** [hook0/hook0#21]
Running `docker compose up -d` on master causes:
> failed to solve: rust:1.8: failed to resolve source metadata for docker.io/library/rust:1.8: docker.io/library/rust:1.8: not found

See:
https://github.com/hook0/hook0/blame/fae4e9676a9d5ac6170ba4d33a325a7e76289220/api/Dockerfile#L1

I think it's meant to be `1.83`, not `1.8`

**Comment by dsferruzza** [comment]
Hi!
Thanks for the report!
This was fixed in 38f7b00e3f74bf1a9a81206cde4874cd278d91e0
