### ISSUE TITLE
SubscriptionsEdit doesn't show headers.

### ISSUE THREAD

**Issue by MaikelActiveAnts** [hook0/hook0#3]
Reproduction:
Create webhook subscription via web interface, add a header, submit.
Open subscription for editing in web interface, headers list is empty.

Headers are there because if you do a get on https://app.hook0.com/api/v1/subscriptions/{subscription_id}, the headers are in the result.

**Comment by dsferruzza** [comment]
Hi!
Thanks for the report!
There was indeed a bug on our UI, which should be fixed now (4484b8fc0d3c77222d4433bf5b6c23f820d610d3).
Let me know if something is still wrong.
